sudo: required
dist: trusty
osx_image: xcode8
language: cpp
os: 
 - linux
 - osx
compiler: 
 - clang
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo easy_install pip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip install --upgrade pyyaml xlsxwriter; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo /usr/bin/env python -m pip install --upgrade pip; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then /usr/bin/env python -m pip install --user --upgrade pyyaml xlsxwriter; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libc6-dev libc6-dev-i386 g++-multilib; fi
script:
  - ./build.sh
