sudo: required
dist: trusty
osx_image: xcode8
language: cpp
os: 
 - linux
 - osx
compiler: 
 - clang
matrix:
 exclude:
   - compiler: clang
     os: linux
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo easy_install pip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo pip install --upgrade pyyaml xlsxwriter; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo /usr/bin/env python -m pip install --upgrade pip; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then /usr/bin/env python -m pip install --user --upgrade pyyaml xlsxwriter; fi
script:
  - ./build.sh
