sudo: required
dist: trusty
osx_image: xcode8
language: cpp
os: 
 - linux
 - osx
compiler: 
 - gcc
 - clang
matrix:
 exclude:
   - compiler: gcc
     os: osx
   - compiler: clang
     os: linux
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; sudo easy_install pip; fi
  - sudo pip install pyyaml xlsxwriter
script:
  - ./build.sh
